### ISSUE TITLE
Signature was invalid

### ISSUE THREAD

**Issue by designed-re** [FSHBOT/kbinxmlcs#4]
kbinxmlcs.KbinException: Signature was invalid. 38 != 0xA0

`var client = new RestClient();
            var req = new RestRequest(new Uri("http://localhost:8080/core/KFC:J:A:A:2019020600/package/list"),Method.GET);
            var res = client.Execute(req);
            var kx = new XmlReader(Encoding.ASCII.GetBytes(res.Content));
            Console.WriteLine(kx.Read().OuterXml);
            await Task.Delay(-1);`

any help?

**Comment by FSH-B** [comment]
Hi, sorry for the late response. This is the likely because the response is encrypted and/or compressed.
